const CRM_CONFIG = {
  SUPABASE_URL: "PASTE_YOUR_SUPABASE_URL_HERE",
  SUPABASE_ANON_KEY: "PASTE_YOUR_SUPABASE_ANON_KEY_HERE",
  ADMIN_PASSWORD: "change-this-password",
  OWNER_WHATSAPP: "61424456407",
  OWNER_EMAIL: "1911310053@qq.com"
};
