
function supabaseHeaders(){return{"apikey":CRM_CONFIG.SUPABASE_ANON_KEY,"Authorization":"Bearer "+CRM_CONFIG.SUPABASE_ANON_KEY,"Content-Type":"application/json","Prefer":"return=representation"}}
function isConfigured(){return CRM_CONFIG.SUPABASE_URL&&!CRM_CONFIG.SUPABASE_URL.includes("PASTE_")}
async function getClientIP(){try{const r=await fetch("https://api.ipify.org?format=json");const d=await r.json();return d.ip||"unknown"}catch(e){return"unknown"}}
function getDeviceInfo(){return{user_agent:navigator.userAgent,language:navigator.language,screen:`${screen.width}x${screen.height}`,timezone:Intl.DateTimeFormat().resolvedOptions().timeZone||""}}
async function supabaseInsert(table,payload){if(!isConfigured()){console.warn("Supabase not configured");return{error:"Supabase not configured"}}const r=await fetch(`${CRM_CONFIG.SUPABASE_URL}/rest/v1/${table}`,{method:"POST",headers:supabaseHeaders(),body:JSON.stringify(payload)});const d=await r.json().catch(()=>null);if(!r.ok)return{error:d||r.statusText};return{data:d}}
async function supabaseSelect(table,query="select=*"){if(!isConfigured())return[];const r=await fetch(`${CRM_CONFIG.SUPABASE_URL}/rest/v1/${table}?${query}`,{headers:supabaseHeaders()});if(!r.ok)return[];return await r.json()}
async function supabasePatch(table,id,payload){const r=await fetch(`${CRM_CONFIG.SUPABASE_URL}/rest/v1/${table}?id=eq.${id}`,{method:"PATCH",headers:supabaseHeaders(),body:JSON.stringify(payload)});return await r.json().catch(()=>null)}
async function trackPageView(){if(location.pathname.includes("crm-"))return;const ip=await getClientIP();const d=getDeviceInfo();await supabaseInsert("page_views",{page:location.pathname.split("/").pop()||"index.html",full_url:location.href,referrer:document.referrer||"",ip_address:ip,user_agent:d.user_agent,language:d.language,screen_size:d.screen,timezone:d.timezone})}
async function submitLeadForm(e){e.preventDefault();const f=e.target,m=document.getElementById("leadFormMessage");m.textContent="正在提交...";const ip=await getClientIP(),d=getDeviceInfo();const payload={name:f.name.value.trim(),wechat:f.wechat.value.trim(),whatsapp:f.whatsapp.value.trim(),email:f.email.value.trim(),registered:f.registered.value,account_type:f.account_type.value,interest:f.interest.value,source_page:f.source_page.value||location.pathname,notes:f.notes.value.trim(),status:"新客户",ip_address:ip,user_agent:d.user_agent,language:d.language,screen_size:d.screen,timezone:d.timezone};const res=await supabaseInsert("leads",payload);if(res.error){m.textContent="提交失败：请检查CRM配置。";m.className="form-message error";return}m.textContent="提交成功，客户经理会尽快联系您。";m.className="form-message success";f.reset();const t=encodeURIComponent(`新客户线索：\n微信：${payload.wechat}\n邮箱：${payload.email||"未填写"}\n账户：${payload.account_type}\n兴趣：${payload.interest}\nIP：${payload.ip_address}`);window.open(`https://wa.me/${CRM_CONFIG.OWNER_WHATSAPP}?text=${t}`,"_blank")}
async function sendLead(e){e.preventDefault();const wechat=document.getElementById("leadWechat")?.value.trim()||"",regEmail=document.getElementById("leadEmail")?.value.trim()||"",note=document.getElementById("leadNote")?.value.trim()||"",ip=await getClientIP(),d=getDeviceInfo();await supabaseInsert("leads",{wechat,email:regEmail,notes:note,source_page:location.pathname,status:"新客户",registered:regEmail?"已开户":"未开户",account_type:"ECN",interest:"网站在线客服",ip_address:ip,user_agent:d.user_agent,language:d.language,screen_size:d.screen,timezone:d.timezone});if(typeof addMsg==="function")addMsg("信息已提交，我们会尽快安排客户经理联系您。","bot");const msg=encodeURIComponent(`您好，我来自TradeMax网站咨询。\n微信：${wechat}\n注册邮箱：${regEmail||"未填写/未开户"}\n备注：${note||"无"}\nIP：${ip}`);window.open(`https://wa.me/${CRM_CONFIG.OWNER_WHATSAPP}?text=${msg}`,"_blank")}
function requireAdminLogin(){if(sessionStorage.getItem("crm_admin_ok")==="1")return;const pwd=prompt("请输入CRM后台密码：");if(pwd===CRM_CONFIG.ADMIN_PASSWORD){sessionStorage.setItem("crm_admin_ok","1")}else{alert("密码错误");location.href="index.html"}}
function adminLogout(){sessionStorage.removeItem("crm_admin_ok");location.href="index.html"}
let leadCache=[];
async function loadLeads(){leadCache=await supabaseSelect("leads","select=*&order=created_at.desc&limit=500");renderLeadStats();renderLeadTable()}
function renderLeadStats(){const today=new Date().toISOString().slice(0,10);document.getElementById("statTotalLeads").textContent=leadCache.length;document.getElementById("statTodayLeads").textContent=leadCache.filter(x=>(x.created_at||"").startsWith(today)).length;document.getElementById("statECNLeads").textContent=leadCache.filter(x=>x.account_type==="ECN").length;document.getElementById("statPendingLeads").textContent=leadCache.filter(x=>!x.status||x.status==="新客户").length}
function renderLeadTable(){const q=(document.getElementById("leadSearch")?.value||"").toLowerCase(),status=document.getElementById("leadStatusFilter")?.value||"";const rows=leadCache.filter(x=>{const hay=`${x.wechat||""} ${x.email||""} ${x.ip_address||""} ${x.notes||""} ${x.whatsapp||""}`.toLowerCase();return(!q||hay.includes(q))&&(!status||x.status===status)});document.getElementById("leadTableBody").innerHTML=rows.map(x=>`<tr><td>${fmt(x.created_at)}</td><td>${esc(x.wechat)}</td><td>${esc(x.email)}</td><td>${esc(x.whatsapp)}</td><td>${esc(x.account_type)}</td><td>${esc(x.interest)}</td><td><select onchange="updateLeadStatus('${x.id}',this.value)">${["新客户","已联系","已开户","已入金","已激活","无效客户"].map(s=>`<option ${x.status===s?"selected":""}>${s}</option>`).join("")}</select></td><td>${esc(x.ip_address)}</td><td>${esc(x.source_page)}</td><td>${esc(x.notes)}</td></tr>`).join("")}
async function updateLeadStatus(id,status){await supabasePatch("leads",id,{status});await loadLeads()}
async function loadAnalytics(){const views=await supabaseSelect("page_views","select=*&order=created_at.desc&limit=1000"),leads=await supabaseSelect("leads","select=*&order=created_at.desc&limit=1000"),today=new Date().toISOString().slice(0,10),ips=new Set(views.map(v=>v.ip_address).filter(Boolean));document.getElementById("statViews").textContent=views.length;document.getElementById("statUniqueIP").textContent=ips.size;document.getElementById("statTodayViews").textContent=views.filter(v=>(v.created_at||"").startsWith(today)).length;document.getElementById("statConversion").textContent=views.length?((leads.length/views.length)*100).toFixed(1)+"%":"0%";const pc={};views.forEach(v=>pc[v.page||"unknown"]=(pc[v.page||"unknown"]||0)+1);document.getElementById("pageRank").innerHTML=Object.entries(pc).sort((a,b)=>b[1]-a[1]).slice(0,10).map(([p,c])=>`<div class="rank-row"><span>${esc(p)}</span><b>${c}</b></div>`).join("");document.getElementById("recentViews").innerHTML=views.slice(0,30).map(v=>`<div class="view-row"><b>${esc(v.ip_address)}</b><span>${esc(v.page)} · ${fmt(v.created_at)}</span></div>`).join("")}
function fmt(s){return s?new Date(s).toLocaleString():""}function esc(v){return String(v||"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
