
function h(){return{"apikey":CRM_CONFIG.SUPABASE_ANON_KEY,"Authorization":"Bearer "+CRM_CONFIG.SUPABASE_ANON_KEY,"Content-Type":"application/json","Prefer":"return=representation"}}function ok(){return CRM_CONFIG.SUPABASE_URL&&!CRM_CONFIG.SUPABASE_URL.includes("PASTE_")}async function ip(){try{let r=await fetch("https://ipapi.co/json/"),d=await r.json();return{ip:d.ip||"unknown",country:d.country_name||"unknown",country_code:d.country_code||"",city:d.city||""}}catch(e){return{ip:"unknown",country:"unknown",country_code:"",city:""}}}function vid(){let v=localStorage.getItem("tm_vid");if(!v){v="v_"+Date.now()+"_"+Math.random().toString(36).slice(2);localStorage.setItem("tm_vid",v)}return v}async function ins(t,p){if(!ok())return{error:"no config"};let r=await fetch(`${CRM_CONFIG.SUPABASE_URL}/rest/v1/${t}`,{method:"POST",headers:h(),body:JSON.stringify(p)});return r.ok?{data:await r.json().catch(()=>null)}:{error:await r.text()}}async function sel(t,q="select=*"){if(!ok())return[];let r=await fetch(`${CRM_CONFIG.SUPABASE_URL}/rest/v1/${t}?${q}`,{headers:h()});return r.ok?await r.json():[]}async function patch(t,id,p){return fetch(`${CRM_CONFIG.SUPABASE_URL}/rest/v1/${t}?id=eq.${id}`,{method:"PATCH",headers:h(),body:JSON.stringify(p)})}
async function trackPageView(){if(location.pathname.includes("crm-"))return;let x=await ip();await ins("page_views",{visitor_id:vid(),page:location.pathname.split("/").pop()||"index.html",full_url:location.href,referrer:document.referrer||"",ip_address:x.ip,country:x.country,country_code:x.country_code,city:x.city,user_agent:navigator.userAgent,language:navigator.language})}
function score(x){let s=0;if(x.wechat)s+=50;if(x.registered==="已开户")s+=30;if(x.email)s+=20;if((x.visit_count||0)>=3)s+=10;if((x.question_count||0)>=2)s+=10;if(x.country_code==="CN")s+=20;if(x.country_code==="AU")s-=20;return Math.max(0,s)}
function pri(x){let s=score(x);if(x.country_code==="AU")return["低优先-澳洲","low"];if(x.country_code==="CN"&&s>=70)return["高优先-中国","hot"];if(s>=80)return["高优先","hot"];if(s>=45)return["中优先","mid"];return["低优先","low"]}
async function submitLeadForm(e){e.preventDefault();let f=e.target,m=document.getElementById("leadFormMessage");m.textContent="正在提交...";let x=await ip();let p={visitor_id:vid(),name:f.name.value,wechat:f.wechat.value,whatsapp:f.whatsapp.value,email:f.email.value,registered:f.registered.value,account_type:f.account_type.value,interest:f.interest.value,source_page:f.source_page.value,notes:f.notes.value,status:"新客户",ip_address:x.ip,country:x.country,country_code:x.country_code,city:x.city,user_agent:navigator.userAgent,lead_score:0};p.lead_score=score(p);let r=await ins("leads",p);if(r.error){m.className="form-message error";m.textContent="提交失败：请检查Supabase配置。";return}m.className="form-message success";m.innerHTML="提交成功，客户经理会尽快联系您。";f.reset()}
async function sendLead(e){e.preventDefault();let x=await ip(),wechat=document.getElementById("leadWechat")?.value||"",email=document.getElementById("leadEmail")?.value||"",notes=document.getElementById("leadNote")?.value||"";await ins("leads",{visitor_id:vid(),wechat,email,notes,registered:email?"已开户":"未开户",account_type:"ECN",interest:"在线客服",status:"新客户",ip_address:x.ip,country:x.country,country_code:x.country_code,city:x.city,user_agent:navigator.userAgent});if(typeof addMsg==="function")addMsg("信息已提交成功，客户经理会尽快联系您。","bot")}
async function logQuestion(q,a){let x=await ip();await ins("chat_logs",{visitor_id:vid(),page:location.pathname.split("/").pop()||"index.html",question:q,answer:a,ip_address:x.ip,country:x.country,country_code:x.country_code,city:x.city,user_agent:navigator.userAgent})}
function requireAdminLogin(){if(sessionStorage.getItem("crm_admin_ok")==="1")return;let p=prompt("请输入CRM后台密码：");if(p===CRM_CONFIG.ADMIN_PASSWORD)sessionStorage.setItem("crm_admin_ok","1");else{alert("密码错误");location.href="index.html"}}function adminLogout(){sessionStorage.removeItem("crm_admin_ok");location.href="index.html"}
let leads=[],views=[],chats=[];function fmt(s){return s?new Date(s).toLocaleString():""}function esc(v){return String(v||"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
async function loadEnterpriseLeads(){leads=await sel("leads","select=*&order=created_at.desc&limit=1000");views=await sel("page_views","select=visitor_id,ip_address,country_code&limit=5000");chats=await sel("chat_logs","select=visitor_id,question&limit=5000");let vc={},qc={};views.forEach(v=>vc[v.visitor_id]=(vc[v.visitor_id]||0)+1);chats.forEach(c=>qc[c.visitor_id]=(qc[c.visitor_id]||0)+1);leads=leads.map(x=>({...x,visit_count:vc[x.visitor_id]||0,question_count:qc[x.visitor_id]||0})).sort((a,b)=>score(b)-score(a));renderEnterpriseStats();renderEnterpriseTable()}
function renderEnterpriseStats(){let today=new Date().toISOString().slice(0,10);statTotalLeads.textContent=leads.length;statTodayLeads.textContent=leads.filter(x=>(x.created_at||"").startsWith(today)).length;statHotLeads.textContent=leads.filter(x=>score(x)>=70).length;statChinaLeads.textContent=leads.filter(x=>x.country_code==="CN").length}
function renderEnterpriseTable(){let q=(leadSearch?.value||"").toLowerCase(),st=leadStatusFilter?.value||"";let rows=leads.filter(x=>(!q||`${x.wechat} ${x.email} ${x.ip_address} ${x.notes} ${x.country}`.toLowerCase().includes(q))&&(!st||x.status===st));leadTableBody.innerHTML=rows.map(x=>{let p=pri(x);return `<tr class="${p[1]}"><td><b>${p[0]}</b><br>${score(x)}分</td><td>${fmt(x.created_at)}</td><td>${esc(x.wechat)}</td><td>${esc(x.email)}</td><td>${esc(x.country)}<br>${esc(x.ip_address)}</td><td>${esc(x.registered)}<br>${esc(x.account_type)}</td><td>${x.visit_count||0}</td><td>${x.question_count||0}</td><td><select onchange="updateLeadStatus('${x.id}',this.value)">${["新客户","已联系","已开户","已入金","已激活","无效客户"].map(s=>`<option ${x.status===s?"selected":""}>${s}</option>`).join("")}</select></td><td>${esc(x.notes)}</td></tr>`}).join("")}
async function updateLeadStatus(id,status){await patch("leads",id,{status});loadEnterpriseLeads()}
async function loadEnterpriseAnalytics(){let v=await sel("page_views","select=*&order=created_at.desc&limit=2000"),c=await sel("chat_logs","select=*&order=created_at.desc&limit=1000"),today=new Date().toISOString().slice(0,10),ips=new Set(v.map(x=>x.ip_address));statViews.textContent=v.length;statUniqueIP.textContent=ips.size;statTodayViews.textContent=v.filter(x=>(x.created_at||"").startsWith(today)).length;statQuestions.textContent=c.length;let pc={};v.forEach(x=>pc[x.page]=(pc[x.page]||0)+1);pageRank.innerHTML=Object.entries(pc).sort((a,b)=>b[1]-a[1]).map(([p,n])=>`<div class="rank-row"><span>${esc(p)}</span><b>${n}</b></div>`).join("");recentViews.innerHTML=v.slice(0,40).map(x=>`<div class="view-row ${x.country_code==='CN'?'china-ip':x.country_code==='AU'?'au-ip':''}"><b>${esc(x.ip_address)} · ${esc(x.country)}</b><span>${esc(x.page)} · ${fmt(x.created_at)}</span></div>`).join("")}
const levs=[1,2,3,5,10,20,30,50,100,200,300,400,500,1000];function applyProductDefaults(){let o=marginSymbol.selectedOptions[0];marginContract.value=o.dataset.contract;marginPrice.value=o.dataset.price;marginLev.innerHTML=levs.filter(v=>v<=+o.dataset.maxlev).map(v=>`<option value="${v}">1:${v}</option>`).join("");marginLev.value=o.dataset.maxlev}function money(n){return "$"+Number(n).toLocaleString(undefined,{maximumFractionDigits:2})}function calcMargin(){marginResult.innerHTML=money((+marginContract.value)*(+marginLots.value)*(+marginPrice.value)/(+marginLev.value))}function calcProfit(){profitResult.innerHTML=money((+profitPips.value)*(+profitLots.value)*(+profitPipValue.value))}function calcPosition(){let risk=(+posBalance.value)*(+posRisk.value)/100;posResult.innerHTML=((risk/((+posSL.value)*(+posPipValue.value))).toFixed(2))+" 标准手<br>风险金额："+money(risk)}
