create extension if not exists "uuid-ossp";
create table if not exists leads (id uuid primary key default uuid_generate_v4(),created_at timestamptz default now(),visitor_id text,name text,wechat text,whatsapp text,email text,registered text,account_type text,interest text,source_page text,notes text,status text default '新客户',lead_score int default 0,visit_count int default 0,question_count int default 0,ip_address text,country text,country_code text,city text,user_agent text);
create table if not exists page_views (id uuid primary key default uuid_generate_v4(),created_at timestamptz default now(),visitor_id text,page text,full_url text,referrer text,ip_address text,country text,country_code text,city text,user_agent text,language text);
create table if not exists chat_logs (id uuid primary key default uuid_generate_v4(),created_at timestamptz default now(),visitor_id text,page text,question text,answer text,ip_address text,country text,country_code text,city text,user_agent text);
alter table leads enable row level security; alter table page_views enable row level security; alter table chat_logs enable row level security;
drop policy if exists "public insert leads" on leads; drop policy if exists "public read leads" on leads; drop policy if exists "public update leads" on leads; drop policy if exists "public insert page_views" on page_views; drop policy if exists "public read page_views" on page_views; drop policy if exists "public insert chat_logs" on chat_logs; drop policy if exists "public read chat_logs" on chat_logs;
create policy "public insert leads" on leads for insert with check (true); create policy "public read leads" on leads for select using (true); create policy "public update leads" on leads for update using (true);
create policy "public insert page_views" on page_views for insert with check (true); create policy "public read page_views" on page_views for select using (true);
create policy "public insert chat_logs" on chat_logs for insert with check (true); create policy "public read chat_logs" on chat_logs for select using (true);
